### ISSUE TITLE
unknown field 'RequestAck'

### ISSUE THREAD

**Issue by soniah** [evalphobia/logrus_fluent#37]
I'm getting the following error in my build. It looks like `fluent.Config` definition has changed.

```
/go/pkg/mod/github.com/evalphobia/logrus_fluent@v0.5.4/config.go:53:3: \
  unknown field 'RequestAck' in struct literal of type fluent.Config
```

Current packages:

```
% grep 'fluent\|logrus' go.mod
        github.com/evalphobia/logrus_fluent v0.5.4
        github.com/fluent/fluent-logger-golang v0.0.0-20180420045249-90f0f0270701 // indirect
        github.com/sirupsen/logrus v1.2.0
```

**Comment by evalphobia** [comment]
@soniah Hi,

`RequestAck` has been added from these versions,

-  fluent-logger-golang@v1.4.0: https://github.com/fluent/fluent-logger-golang/releases/tag/v1.4.0
- logrus_fluent@v0.5.3: https://github.com/evalphobia/logrus_fluent/pull/30

Update `fluent/fluent-logger-golang`, otherwise downgrade `evalphobia/logrus_fluent`.

**Comment by soniah** [comment]
Thanks, I'll give that a go.
